development:
  adapter: mysql
  encoding: utf8
  database: CareerCommunity_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: CareerCommunity_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: CareerCommunity
  username: root
  password: ***REMOVED***
  host: localhost
