development:
  mem_limit: 64M
  max_matches: 1000
  charset_type: utf-8

test:
  mem_limit: 64M
  max_matches: 1000
  charset_type: utf-8

production:
  mem_limit: 64M
  max_matches: 1000
  charset_type: utf-8
