development:
  mem_limit: 512M
  charset_type: zh_cn.utf-8
  charset_dictpath: /Users/tomato/Dev/git/projects/CareerCommunity/db/sphinx/dict
  searchd_file_path: /Users/tomato/Dev/git/projects/CareerCommunity/db/sphinx/development
  config_file: /Users/tomato/Dev/git/projects/CareerCommunity/config/development.sphinx.conf

test:
  mem_limit: 512M
  charset_type: zh_cn.utf-8
  charset_dictpath: /Users/tomato/Dev/git/projects/CareerCommunity/db/sphinx/dict
  searchd_file_path: /Users/tomato/Dev/git/projects/CareerCommunity/db/sphinx/test
  config_file: /Users/tomato/Dev/git/projects/CareerCommunity/config/test.sphinx.conf

production:
  mem_limit: 1024M
  charset_type: zh_cn.utf-8
  charset_dictpath: /home/tomato/websites/app/CareerCommunity/shared/sphinx/dict
  searchd_file_path: /home/tomato/websites/app/CareerCommunity/shared/sphinx/production
  config_file: /home/tomato/websites/app/CareerCommunity/shared/sphinx/conf/production.sphinx.conf
