development:
  mem_limit: 512M
  charset_type: zh_cn.utf-8
  charset_dictpath: Users/tomato/Dev/sphinx/coreseek_fulltext_2.5.source/dict

test:
  mem_limit: 512M
  charset_type: zh_cn.utf-8

production:
  mem_limit: 512M
  charset_type: zh_cn.utf-8
