production:
#  port: 3312
  morphology: stem_en
  mem_limit: 1024M
  charset_type: zh_cn.utf-8
  sql_query_pre: SET NAMES utf8
  sql_range_step: 2048
  sql_ranged_throttle: 0
  searchd_file_path: /home/tomato/websites/app/CareerCommunity/shared/sphinx/production
  config_file: /home/tomato/websites/app/CareerCommunity/shared/sphinx/conf/production.sphinx.conf
  searchd_log_file: /home/tomato/websites/app/CareerCommunity/shared/log/searchd.log
  query_log_file: /home/tomato/websites/app/CareerCommunity/shared/log/searchd.query.log
  pid_file: /home/tomato/websites/app/CareerCommunity/shared/log/searchd.production.pid

development:
#  port: 3312
  morphology: stem_en
  mem_limit: 512M
  charset_type: zh_cn.utf-8
  sql_query_pre: SET NAMES utf8
  sql_range_step: 2048
  sql_ranged_throttle: 0
  searchd_file_path: /Users/tomato/Dev/git/projects/CareerCommunity/db/sphinx/development
  config_file: /Users/tomato/Dev/git/projects/CareerCommunity/config/development.sphinx.conf
  searchd_log_file: /Users/tomato/Dev/git/projects/CareerCommunity/log/searchd.log
  query_log_file: /Users/tomato/Dev/git/projects/CareerCommunity/log/searchd.query.log
  pid_file: /Users/tomato/Dev/git/projects/CareerCommunity/log/searchd.development.pid

test:
#  port: 3312
  morphology: stem_en
  mem_limit: 512M
  charset_type: zh_cn.utf-8
  sql_query_pre: SET NAMES utf8
  sql_range_step: 2048
  sql_ranged_throttle: 0
  searchd_file_path: /Users/tomato/Dev/git/projects/CareerCommunity/db/sphinx/test
  config_file: /Users/tomato/Dev/git/projects/CareerCommunity/config/test.sphinx.conf
  searchd_log_file: /Users/tomato/Dev/git/projects/CareerCommunity/log/searchd.log
  query_log_file: /Users/tomato/Dev/git/projects/CareerCommunity/log/searchd.query.log
  pid_file: /Users/tomato/Dev/git/projects/CareerCommunity/log/searchd.test.pid
